import type { CircleLayerSpecification, SymbolLayerSpecification } from 'maplibre-gl';
import {
  EXPLORER_CLUSTER_PIN_IMAGE_ID,
  EXPLORER_CLUSTER_SELECTED_IMAGE_ID,
  EXPLORER_PIN_IMAGE_ID,
  EXPLORER_PIN_SELECTED_IMAGE_ID,
  explorerPinTokens,
} from '../../lib/explorerPinStyle';

export const LISTINGS_SOURCE_ID = 'swing-listings';
export const LISTING_INTERACTION_LAYER_ID = 'listing-interaction-hit';

const hoverState: any = ['boolean', ['feature-state', 'hover'], false];
const pulseState: any = ['coalesce', ['feature-state', 'pulse'], 0.5];
const pulseOpacity: any = [
  'interpolate',
  ['linear'],
  pulseState,
  0,
  0.18,
  0.5,
  0.22,
  1,
  0.18,
];
const pulseRadius: any = [
  'interpolate',
  ['linear'],
  pulseState,
  0,
  12.4,
  0.5,
  13.3,
  1,
  12.4,
];
const selectedPulseOpacity: any = [
  'interpolate',
  ['linear'],
  pulseState,
  0,
  0.5,
  0.5,
  0.56,
  1,
  0.5,
];
const selectedPulseRadius: any = [
  'interpolate',
  ['linear'],
  pulseState,
  0,
  19.5,
  0.5,
  20.4,
  1,
  19.5,
];

const pinOpacity: any = [
  'case',
  hoverState,
  explorerPinTokens.hoverOpacity,
  explorerPinTokens.idleOpacity,
];

const labelText: any = [
  'format',
  ['get', 'labelTitle'],
  {
    'font-scale': 1,
    'text-font': ['literal', ['Open Sans Bold', 'Arial Unicode MS Bold']],
  },
  '\n',
  {},
  ['get', 'labelSubtitle'],
  {
    'font-scale': 0.72,
    'text-font': ['literal', ['Open Sans Regular', 'Arial Unicode MS Regular']],
  },
];

const venueLabelLayout: any = {
  'text-field': labelText,
  'text-size': [
    'interpolate',
    ['linear'],
    ['zoom'],
    11,
    10.5,
    15,
    12,
    17,
    13,
  ],
  'text-font': ['Open Sans Bold', 'Arial Unicode MS Bold'],
  'text-anchor': 'bottom',
  'text-offset': [0, -5.15],
  'text-line-height': 0.92,
  'text-letter-spacing': 0.02,
  'text-max-width': 12,
  'text-allow-overlap': false,
  'text-ignore-placement': false,
  'text-pitch-alignment': 'viewport',
  'text-rotation-alignment': 'viewport',
};

const venueLabelPaint: any = {
  'text-color': '#F5F5F5',
  'text-halo-color': 'rgba(10,12,16,0.86)',
  'text-halo-width': 1.35,
  'text-halo-blur': 0.85,
};

export const listingLayers: Array<CircleLayerSpecification | SymbolLayerSpecification> = [
  {
    id: 'listing-cluster-ripple',
    type: 'circle',
    source: LISTINGS_SOURCE_ID,
    filter: ['has', 'point_count'],
    paint: {
      'circle-pitch-alignment': 'viewport',
      'circle-color': 'rgba(245,245,245,0.16)',
      'circle-radius': [
        'case',
        hoverState,
        ['step', ['get', 'point_count'], 27, 10, 32, 50, 38],
        ['+', ['step', ['get', 'point_count'], 19, 10, 23, 50, 28], ['*', pulseState, 5]],
      ],
      'circle-stroke-color': 'rgba(245,245,245,0.24)',
      'circle-stroke-width': ['case', hoverState, 1.4, 0.8],
      'circle-opacity': ['case', hoverState, 0.3, ['+', 0.08, ['*', pulseState, 0.12]]],
      'circle-blur': 0.42,
      'circle-opacity-transition': { duration: 120, delay: 0 },
      'circle-radius-transition': { duration: 120, delay: 0 },
    },
  },
  {
    id: 'listing-cluster-glow',
    type: 'circle',
    source: LISTINGS_SOURCE_ID,
    filter: ['has', 'point_count'],
    paint: {
      'circle-pitch-alignment': 'viewport',
      'circle-color': ['case', hoverState, 'rgba(255,77,94,0.48)', 'rgba(197,29,52,0.32)'],
      'circle-radius': [
        'case',
        hoverState,
        ['step', ['get', 'point_count'], 26, 10, 31, 50, 37],
        ['step', ['get', 'point_count'], 22, 10, 26, 50, 31],
      ],
      'circle-opacity': ['case', hoverState, 0.54, 0.36],
      'circle-blur': 0.48,
      'circle-opacity-transition': { duration: 120, delay: 0 },
      'circle-radius-transition': { duration: 120, delay: 0 },
    },
  },
  {
    id: 'listing-cluster-base',
    type: 'circle',
    source: LISTINGS_SOURCE_ID,
    filter: ['has', 'point_count'],
    paint: {
      'circle-pitch-alignment': 'viewport',
      'circle-color': ['case', hoverState, '#240810', '#0F1115'],
      'circle-radius': [
        'case',
        hoverState,
        ['step', ['get', 'point_count'], 17, 10, 20, 50, 24],
        ['step', ['get', 'point_count'], 15, 10, 18, 50, 22],
      ],
      'circle-stroke-color': ['case', hoverState, '#FF4D5E', '#C51D34'],
      'circle-stroke-width': ['case', hoverState, 2.2, 1.6],
      'circle-opacity': 0.94,
      'circle-stroke-opacity': 0.96,
      'circle-opacity-transition': { duration: 120, delay: 0 },
      'circle-radius-transition': { duration: 120, delay: 0 },
    },
  },
  {
    id: 'listing-clusters',
    type: 'symbol',
    source: LISTINGS_SOURCE_ID,
    filter: ['has', 'point_count'],
    layout: {
      'icon-image': EXPLORER_CLUSTER_PIN_IMAGE_ID,
      'icon-size': ['step', ['get', 'point_count'], 1.0, 10, 1.08, 50, 1.18],
      'icon-anchor': 'center',
      'icon-allow-overlap': true,
      'icon-ignore-placement': true,
      'icon-pitch-alignment': 'viewport',
      'icon-rotation-alignment': 'viewport',
    },
    paint: {
      'icon-opacity': ['case', hoverState, 1.0, 0.94],
      'icon-opacity-transition': { duration: 100, delay: 0 },
    },
  },
  {
    id: 'listing-cluster-count',
    type: 'symbol',
    source: LISTINGS_SOURCE_ID,
    filter: ['has', 'point_count'],
    layout: {
      'visibility': 'none',
      'text-field': ['get', 'point_count_abbreviated'],
      'text-size': 11.5,
      'text-font': ['Open Sans Bold', 'Arial Unicode MS Bold'],
      'text-anchor': 'top',
      'text-offset': [0, 1.55],
      'text-allow-overlap': true,
      'text-ignore-placement': true,
      'text-pitch-alignment': 'viewport',
      'text-rotation-alignment': 'viewport',
    },
    paint: {
      'text-color': '#F5F5F5',
      'text-halo-color': 'rgba(8,10,14,0.92)',
      'text-halo-width': 1,
      'text-opacity': ['case', hoverState, 1, 0.9],
      'text-opacity-transition': { duration: 100, delay: 0 },
    },
  },
  {
    id: LISTING_INTERACTION_LAYER_ID,
    type: 'circle',
    source: LISTINGS_SOURCE_ID,
    filter: ['!', ['has', 'point_count']],
    paint: {
      'circle-pitch-alignment': 'viewport',
      'circle-radius': 22,
      'circle-color': '#000000',
      'circle-opacity': 0.001,
      'circle-stroke-opacity': 0,
    },
  },
  {
    id: 'listing-pin-ripple',
    type: 'circle',
    source: LISTINGS_SOURCE_ID,
    filter: ['!', ['has', 'point_count']],
    paint: {
      'circle-pitch-alignment': 'map',
      'circle-color': 'rgba(245,245,245,0.16)',
      'circle-radius': ['case', hoverState, 18, pulseRadius],
      'circle-stroke-color': 'rgba(245,245,245,0.24)',
      'circle-stroke-width': ['case', hoverState, 1.15, 0.65],
      'circle-opacity': ['case', hoverState, 0.2, pulseOpacity],
      'circle-blur': 0.44,
    },
  },
  {
    id: 'listing-pin-glow',
    type: 'circle',
    source: LISTINGS_SOURCE_ID,
    filter: ['!', ['has', 'point_count']],
    paint: {
      'circle-pitch-alignment': 'map',
      'circle-color': 'rgba(197,29,52,0.35)',
      'circle-radius': ['case', hoverState, 15, ['+', 11, ['*', ['-', pulseState, 0.5], 1.2]]],
      'circle-opacity': ['case', hoverState, 0.34, ['+', 0.2, ['*', ['-', pulseState, 0.5], 0.04]]],
      'circle-blur': 0.55,
    },
  },
  {
    id: 'listing-pins',
    type: 'symbol',
    source: LISTINGS_SOURCE_ID,
    filter: ['!', ['has', 'point_count']],
    layout: {
      'icon-image': EXPLORER_PIN_IMAGE_ID,
      'icon-size': explorerPinTokens.idleScale,
      'icon-anchor': 'bottom',
      'icon-allow-overlap': true,
      'icon-ignore-placement': true,
      'icon-pitch-alignment': 'viewport',
      'icon-rotation-alignment': 'viewport',
    },
    paint: {
      'icon-opacity': pinOpacity,
    },
  },
  {
    id: 'listing-labels-nearby',
    type: 'symbol',
    source: LISTINGS_SOURCE_ID,
    filter: ['!', ['has', 'point_count']],
    minzoom: 14.4,
    layout: venueLabelLayout,
    paint: {
      ...venueLabelPaint,
      'text-opacity': [
        'interpolate',
        ['linear'],
        ['zoom'],
        14.4,
        0,
        15.4,
        0.62,
        16.6,
        0.86,
      ],
    },
  },
  {
    id: 'listing-labels-hover',
    type: 'symbol',
    source: LISTINGS_SOURCE_ID,
    filter: ['!', ['has', 'point_count']],
    minzoom: 11.2,
    layout: venueLabelLayout,
    paint: {
      ...venueLabelPaint,
      'text-color': '#FFFFFF',
      'text-halo-color': 'rgba(197,29,52,0.42)',
      'text-halo-width': 1.65,
      'text-halo-blur': 1,
      'text-opacity': ['case', hoverState, 1, 0],
      'text-opacity-transition': { duration: 140, delay: 0 },
    },
  },
  {
    id: 'selected-listing-ripple',
    type: 'circle',
    source: LISTINGS_SOURCE_ID,
    filter: ['==', ['get', 'listingId'], ''],
    paint: {
      'circle-pitch-alignment': 'map',
      'circle-color': 'rgba(245,245,245,0.24)',
      'circle-radius': selectedPulseRadius,
      'circle-stroke-color': 'rgba(245,245,245,0.36)',
      'circle-stroke-width': 1.4,
      'circle-opacity': selectedPulseOpacity,
      'circle-blur': 0.5,
      'circle-opacity-transition': { duration: 120, delay: 0 },
      'circle-radius-transition': { duration: 120, delay: 0 },
    },
  },
  {
    id: 'selected-listing-glow',
    type: 'circle',
    source: LISTINGS_SOURCE_ID,
    filter: ['==', ['get', 'listingId'], ''],
    paint: {
      'circle-pitch-alignment': 'map',
      'circle-color': 'rgba(255,77,94,0.45)',
      'circle-radius': selectedPulseRadius,
      'circle-opacity': selectedPulseOpacity,
      'circle-blur': 0.44,
      'circle-opacity-transition': { duration: 120, delay: 0 },
      'circle-radius-transition': { duration: 120, delay: 0 },
    },
  },
  {
    id: 'selected-listing',
    type: 'symbol',
    source: LISTINGS_SOURCE_ID,
    filter: ['==', ['get', 'listingId'], ''],
    layout: {
      'icon-image': EXPLORER_PIN_SELECTED_IMAGE_ID,
      'icon-size': explorerPinTokens.selectedScale,
      'icon-anchor': 'bottom',
      'icon-allow-overlap': true,
      'icon-ignore-placement': true,
      'icon-pitch-alignment': 'viewport',
      'icon-rotation-alignment': 'viewport',
    },
    paint: {
      'icon-opacity': explorerPinTokens.selectedOpacity,
      'icon-opacity-transition': { duration: 120, delay: 0 },
    },
  },
  {
    id: 'selected-listing-label',
    type: 'symbol',
    source: LISTINGS_SOURCE_ID,
    filter: ['==', ['get', 'listingId'], ''],
    minzoom: 10.8,
    layout: {
      ...venueLabelLayout,
      'text-offset': [0, -5.9],
    },
    paint: {
      ...venueLabelPaint,
      'text-color': '#FFFFFF',
      'text-halo-color': 'rgba(197,29,52,0.5)',
      'text-halo-width': 1.8,
      'text-halo-blur': 1.1,
      'text-opacity': [
        'interpolate',
        ['linear'],
        ['zoom'],
        10.8,
        0,
        11.45,
        1,
      ],
      'text-opacity-transition': { duration: 160, delay: 0 },
    },
  },
];
